### ISSUE TITLE
[PE-D][Tester E] Email does not need to have a domain name extension

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T08-2/tp#131]
## How to replicate:

Add a new user with an email that does not have a domain name extension (eg .com)

eg add n/John Doe p/98765432 e/johnd@example a/John street, block 123,
#01-01

## Expected Behaviour:

Throw an error stating that a domain name extension is required

## Actual Behaviour:
Customer is added to the address book.

![Screenshot 2024-04-05 at 4.28.42 PM.png](https://raw.githubusercontent.com/saiutkarsh33/ped/main/files/765e0b67-9255-48e9-85a1-6da1ac0dd42d.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: saiutkarsh33/ped#3

**Comment by Joelwang22** [comment]
Not necessary to change but can mention in UG?

**Comment by Joelwang22** [comment]
Accepting supposedly invalid values (e.g., end date is earlier than start date; February 30th) is, while not ideal, not necessarily incorrect either (i.e., adopting a [garbage-in garbage-out](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out) approach to input validation). However, if such data can make other things go haywire (e.g., crash the app, corrupt the data file), accepting them can be considered a bug, and fixed.

Does not make things go haywire, Closed
