### ISSUE TITLE
[PE-D][Tester E] Example of added customer doesent work in docs

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T08-2/tp#137]
## Expected docs

An eg of adding a customer that works and does not throw an error

## Actual docs 

The second example throws an error

![Screenshot 2024-04-05 at 4.42.06 PM.png](https://raw.githubusercontent.com/saiutkarsh33/ped/main/files/bcb2787b-02c1-4b5d-918b-7f003e0a697b.png)

![Screenshot 2024-04-05 at 4.42.02 PM.png](https://raw.githubusercontent.com/saiutkarsh33/ped/main/files/4f262255-ebeb-4fe6-a9de-978df028ba12.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: saiutkarsh33/ped#4

**Comment by Joelwang22** [comment]
Except it does work...?
![Issue #137](https://github.com/AY2324S2-CS2103T-T08-2/tp/assets/122248271/2b1299e6-fda4-46fa-8182-ee2fb9343d1f)
