### ISSUE TITLE
[PE-D][Tester A] Large Item Product Costs and Sales is not shown properly in Orders

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T08-2/tp#144]
Similar to the issues in the Menu Section, Large Product Costs and Sales go off the screen and cannot be seen properly in the Orders Section.

![image.png](https://raw.githubusercontent.com/SherisseTJW/ped/main/files/a6be3b6b-884f-47cb-a43b-8b5deea044e3.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: SherisseTJW/ped#11

**Comment by chonghaoen** [comment]
resizing screen will help, also ignored under garbage-in garbage-out approach
