### ISSUE TITLE
[PE-D][Tester C] Invalid command format without clear reasoning

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T08-2/tp#149]
![image.png](https://raw.githubusercontent.com/darryl-chan/ped/main/files/b6148547-d124-4748-9786-4960fb880be0.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: darryl-chan/ped#4

**Comment by bertrandong** [comment]
Considered as making the error message more specific, and thus would be an enhancement
