### ISSUE TITLE
[PE-D][Tester A] Invalid Dates are accepted as Deadline but are changed to a different day in the UI

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T08-2/tp#150]
As seen in the Screenshot below, the Order has a deadline of 29 February 2024, which is valid. However, the actual command I had entered was: `order p/123 by/31/02/2024`, which is different from the deadline shown on the UI

![image.png](https://raw.githubusercontent.com/SherisseTJW/ped/main/files/e58c8e1c-2d70-4269-8a7e-7f2166ed6372.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: SherisseTJW/ped#12

**Comment by Joelwang22** [comment]
Duplicate with Issue#168
