### ISSUE TITLE
[PE-D][Tester B] Simplification of ordering mechanism

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T08-2/tp#183]
As far as I know executing `order` command has no noticeable visual changes on the application. Perhaps the `order` command can be simplified to a single command rather an executing `order` then `product` command to improve the ease of use for the user?

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: SimKianSeng/ped#14

**Comment by 0-yibai** [comment]
Thank you for your suggestion of feature improvement. We have taken note of this and shall close the issue for now.
